obj-m := zeroVisor.o
zeroVisor-objs := zv_core.o \
				zv_log.o \
				zv_mmu.o \
				zv_mem_manager.o \
				asm.o \
				zv_exit_callback.o \
				zv_func_replace.o \
				zv_func_search.o \
				zv_dev_memory.o 